spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init.encoding: UTF-8
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: "1"
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
logging:
  file.name: logs/application.log
  level:
    '[org.hibernate]':
      SQL: DEBUG
      '[type.descriptor.sql.BasicBinder]': TRACE
      '[resource.transaction]': DEBUG
    '[org.springframework.transaction.interceptor]': TRACE
    '[org.springframework.orm.jpa.JpaTransactionManager]': DEBUG
    '[org.springframework.jdbc.datasource.DataSourceTransactionManager]': DEBUG
springdoc:
  swagger-ui:
    enabled: true
    path: /